@echo off
setlocal EnableExtensions
set "arg1=%~1"
set "arg2=%~2"
set "OBJDUMP=%~3"
if "%arg2%"=="" set "arg2=%arg1%"
set "ICS_DIR=%~dp0"

REM If no objdump path was provided (manual invocation), fall back to PATH.
if "%OBJDUMP%"=="" set "OBJDUMP=arm-none-eabi-objdump.exe"

REM Best-effort cleanup of prior outputs so stale/locked files don't mask failures.
if exist "%arg2%.txt"  del /f /q "%arg2%.txt"  >nul 2>&1
if exist "%arg2%.rmap" del /f /q "%arg2%.rmap" >nul 2>&1

REM Sanity check: the resolved objdump must exist (or be locatable on PATH).
REM CMake build commands call gcc/objcopy by absolute path, so the toolchain
REM bin dir is NOT on PATH inside post-build steps; CMakeLists.txt therefore
REM passes the explicit objdump path as %3.
if exist "%OBJDUMP%" goto objdump_resolved
where "%OBJDUMP%" >nul 2>&1
if errorlevel 1 (
    echo convert.bat: ERROR - objdump not found: "%OBJDUMP%" 1>&2
    exit /b 1
)
:objdump_resolved

REM Sanity check: the input ELF must exist in the current directory.
if not exist "%arg1%.elf" (
    echo convert.bat: ERROR - input ELF "%arg1%.elf" not found in "%CD%" 1>&2
    exit /b 1
)

REM Use --dwarf=info,abbrev,str,str-offsets instead of -W: that's everything
REM ElfMapConverter.exe needs (symbol names, types, addresses, sizes) and
REM skips .debug_loclists / .debug_line / .debug_frame / .debug_ranges, which
REM on this build can be malformed and cause objdump to either error out or
REM produce a multi-GB dump.
REM The retry covers the rare case where the output file is briefly locked
REM by the indexer / VS Code preview / antivirus right after a build.
set _tries=0
:objdump_retry
set /a _tries+=1
"%OBJDUMP%" --dwarf=info,abbrev,str,str-offsets "%arg1%.elf" > "%arg2%.txt" 2>nul
if not errorlevel 1 goto objdump_done
if %_tries% lss 5 (
    echo convert.bat: objdump write to "%arg2%.txt" failed ^(errorlevel %errorlevel%^), retry %_tries% ...
    if exist "%arg2%.txt" del /f /q "%arg2%.txt" >nul 2>&1
    >nul ping -n 2 127.0.0.1
    goto objdump_retry
)
echo convert.bat: ERROR - objdump failed to write "%arg2%.txt" after %_tries% attempts 1>&2
exit /b 1
:objdump_done

"%ICS_DIR%ElfMapConverter.exe" "%arg2%.txt"
if errorlevel 1 (
    echo convert.bat: ERROR - ElfMapConverter failed ^(exit %errorlevel%^) 1>&2
    exit /b 1
)

if not exist "%arg2%.rmap" (
    echo convert.bat: ERROR - "%arg2%.rmap" was not generated by ElfMapConverter 1>&2
    exit /b 1
)

copy /y "%arg2%.rmap" "%ICS_DIR%%arg2%_conv.map" >nul
if errorlevel 1 (
    echo convert.bat: ERROR - failed to copy "%arg2%.rmap" to "%ICS_DIR%%arg2%_conv.map" 1>&2
    exit /b 1
)

endlocal
exit /b 0